stages :
  
- setup
- build
- test

setup_python:
  stage: setup
  script: 
- pip install -r requirements.txt

build_python:
  stage: build
  script: 
- python hello_world.py build

test_python:
  stage: test
  script: 
- python -m unittest discover


 